/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeremy_ndktest_StudentUtils */

#ifndef _Included_com_jeremy_ndktest_StudentUtils
#define _Included_com_jeremy_ndktest_StudentUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeremy_ndktest_StudentUtils
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jeremy_ndktest_StudentUtils_getName(JNIEnv *env,jobject /* this */);

#ifdef __cplusplus
}
#endif
#endif
