/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <android/log.h>
#include "include/Student.h"
#include "include/com_jeremy_ndktest_StudentUtils.h"
/* Header for class com_jeremy_ndktest_StudentUtils */

#define LOG_TAG "NATIVE_OUTPUT"
#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, LOG_TAG, __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

#ifdef __cplusplus
extern "C"
#endif
/*
 * Class:     com_jeremy_ndktest_StudentUtils
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jeremy_ndktest_StudentUtils_getName(JNIEnv *env,jobject /* this */){
  Student student;
  LOGE("执行了方法");
 // LOGE(student.getName());
//  LOGE(student.getName().c_str());
  return env->NewStringUTF(student.getName().c_str());
}


